version: '3.9'

services:
  redis:
    image: 'redis:7.2-alpine'
    restart: unless-stopped
    command: --loglevel warning --maxmemory-policy noeviction
    volumes:
      - redis-data:/data
    ports:
      - '6379:6379'
    healthcheck:
      test: ['CMD-SHELL', 'redis-cli ping']
      interval: 5s       # Check every 5 seconds
      timeout: 5s        # Allow up to 5 seconds for a response
      retries: 3         # Fail after 3 unsuccessful attempts
      start_period: 5s   # Start health checks after 5 seconds
    networks:
      - app-network

volumes:
  redis-data:

networks:
  app-network:
